# File: azure-pipelines.yml
trigger:
- master

variables:
  - group: quick-start-vg
  - name: APP_NAME
    value: quick-start-app
  - name: AZP_POOL
    value: my-special-pool
  - name: TEMPLATE_DIR
    value: .bedrock-templates
  # - template: $TEMPLATE_DIR/app-variables.yml  # Template reference

stages:
  - stage: build
    jobs:
      - job: run_build_push_acr
        pool:
          vmImage: ubuntu-latest
        steps:
        - template: $TEMPLATE_DIR/azure-login.yml  # Template reference
          parameters:
            appId: $(SP_APP_ID)
            password: $(SP_PASS)
            tenantId: $(SP_TENANT)
        - template: $TEMPLATE_DIR/container-build-strategy.yml  # Template reference
          parameters:
            downloadTools: false
            imageRepoType: ACR
            imageName: "$(APP_NAME)-$(Build.SourceBranchName)"
            imageTag: $(Build.BuildNumber)
            buildArgs:
            - AZP_POOL
            - ACR_NAME
  - stage: hld_update
    dependsOn: build
    condition: succeeded('build')
    jobs:
      - job: update_image_tag
        pool:
          vmImage: ubuntu-latest
        steps:
        - template: $TEMPLATE_DIR/git-update-strategy.yml  # Template reference
          parameters:
            downloadFab: true
            downloadTools: true
            azureContainerRegistry: $(ACR_NAME) 
            gitUpdateType: HLD
            gitRepoURL: $(HLD_REPO)
            gitRepoName: 'quick-start-hld'
            gitBranchName: $(Build.SourceBranchName)
            gitAccessToken: $(PAT) 
            serviceName: $(APP_NAME)
            imageTag: $(Build.BuildNumber)