# File: azure-pipelines.yml
trigger:
- master

variables:
  - group: agent-build-vg

extends:
  template: docker-build-strategy.yml
  parameters:
    imageRepoType: acr
    ImageName: "quick-start-app-$(Build.SourceBranchName)" # set to a non-boolean value to have the build fail
    ImageTag: "v0.1" # set to a non-boolean value to have the build fail
    BuildArgVariableGroup: 'agent-build-vg'
    BuildArgs:
    - AZP_POOL
    - ACR_NAME
