# File: azure-pipelines.yml
trigger:
- master

variables:
  - group: agent-build-vg

stages:
  - stage: build
    jobs:
      - job: run_build_push_acr
        pool:
          vmImage: ubuntu-latest
        steps:
        - template: Container-Build-Strategy.yml  # Template reference
          parameters:
            imageRepoType: ACR
            imageName: "quick-start-app-$(Build.SourceBranchName)"
            imageTag: "v0.1"
            buildArgs:
            - AZP_POOL
            - ACR_NAME

# extends:
#   template: Container-Build-Strategy.yml
#   parameters:
#     imageRepoType: ACR
#     imageName: "quick-start-app-$(Build.SourceBranchName)"
#     imageTag: "v0.1"
#     buildArgs:
#     - AZP_POOL
#     - ACR_NAME
