# File: azure-pipelines.yml
trigger:
- master

variables:
  - group: agent-build-vg

extends:
- template: Container-Build-Strategy.yml
  parameters:
    imageRepoType: ACR
    imageName: "quick-start-app-$(Build.SourceBranchName)"
    imageTag: "v0.1"
    buildArgs:
    - AZP_POOL
    - ACR_NAME
