# File: azure-pipelines.yml
trigger:
- master

variables:
  - group: agent-build-vg
  # - template: app-variables.yml  # Template reference
  #  ^^ echo My favorite vegetable is ${{ variables.favoriteVeggie }}

stages:
  - stage: build
    jobs:
      - job: run_build_push_acr
        pool:
          vmImage: ubuntu-latest
        steps:
        # - template: azure-login.yml  # Template reference
        #   parameters:
        #     appId: $(SP_CLIENT_ID)
        #     password: $(SP_CLIENT_PASS)
        #     tenantId: $(TENANT_ID)
        - template: container-build-strategy.yml  # Template reference
          parameters:
            downloadTools: false
            imageRepoType: ACR
            imageName: "quick-start-app-$(Build.SourceBranchName)"
            imageTag: "v0.1"
            buildArgs:
            - AZP_POOL
            - ACR_NAME
  - stage: hld_update
    dependsOn: build
    condition: succeeded('build')
    jobs:
      - job: update_image_tag
        pool:
          vmImage: ubuntu-latest
        steps:
        - script: |-
            echo "I need TODO this"
          displayName: Debugging messages

# extends:
#   template: Container-Build-Strategy.yml
#   parameters:
#     imageRepoType: ACR
#     imageName: "quick-start-app-$(Build.SourceBranchName)"
#     imageTag: "v0.1"
#     buildArgs:
#     - AZP_POOL
#     - ACR_NAME
